terraform provider implemented
mkuptsov/movie-reviews pull request #2
Opened 2023-07-13 07:33 UTC by mkuptsov

2023-07-13 07:58 UTC, unspectd commented on terraform_provider/datasource_item.go
> +			err = rd.Set("role", "")
Это очень похоже на удаление ресурса SetId(""),
но кажется если датасорс не может найти что-то, то он должен просто выдавать ошибку

2023-07-13 07:58 UTC, unspectd commented on terraform_provider/datasource_item.go
> +	err = rd.Set("role", user.Role)
👍

2023-07-13 08:00 UTC, unspectd commented on terraform_provider/resource_item.go
> +	err = rd.Set("user_role", role)
В схеме же нет user_role.
Мне кажется на этом этапе у тебя уже есть user_id и role которые ты получаешь из ResourceData и они не меняются, так что можно и не сетать ничего

2023-07-13 08:03 UTC, unspectd commented on terraform_provider/resource_item.go
> +	err = rd.Set("user_id", user.ID)
Кажется на этом этапе единственное поле которое ридом ты можешь обновить это "role". Для того чтобы понять, что роль была изменена вне терраформа и чтобы терраформ еще обратно установил

2023-07-13 08:04 UTC, unspectd commented on terraform_provider/resource_item.go
> +	err = rd.Set("user_id", userID)
По-моему ничего сохранять в ResourceData на делите не требуется, так как терраформ снесет данные об этом ресурсе по окончанию удаления. То есть в стейте ничего не останется после удаления ресурса. Главное перед этим процессом юзеру скинуть роль

2023-07-13 08:05 UTC, unspectd requested changes
Глянь коментарии

2023-07-14 16:35 UTC, mkuptsov commented on terraform_provider/resource_item.go
> +	err = rd.Set("user_role", role)
с id я согласен, а с role я опять упираюсь в непонимание, как это работает :)
когда я запускаю terraform apply, он делает read ресурсам, в результате он должен сделать rd.Set("role",) каждому ресурсу в стейт файле, чтобы сравнить с тем, что указано в .tf. Если есть отличия между тем, что есть в сервисе(а после read и в стейт файле) и .tf, терраформ должен запустить update, который изменит роль в сервисе и, если это удалось, сделать rd.Set("role",), чтобы в стейт файле была актуальная инфа. я неправильно понимаю?

2023-07-14 16:53 UTC, unspectd commented on terraform_provider/resource_item.go
> +	err = rd.Set("user_role", role)
Ты просто вначале берешь эти данные из ResourceData

```
	userID := rd.Get("user_id").(int)
	role := rd.Get("role").(string)
```

То есть они у тебя есть на начало выполнения CreateOrUpdate, потом ты их не меняешь и обратно устанавливаешь в ResourceData. Эти данные уже там есть

2023-07-15 22:22 UTC, unspectd approved these changes

2023-07-16 14:32 UTC, merged